# Generated by Django 4.1.3 on 2022-11-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('stop_date', models.DateTimeField(verbose_name='Дедлайн')),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'ordering': ['-stop_date'],
            },
        ),
    ]
