# Generated by Django 4.1.3 on 2022-11-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_file_alter_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.file'),
        ),
    ]
